l_english:
 DIVISION_QUEUED:0 "$N$ Squad"
 DIVISIONS_QUEUED:0 "$N$ Squads"
 DEPLOYMENT_DIVISION_LABEL:0 "Squad"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GClick to edit Squad template§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§GClick to view Squad template§!"
 DEPLOYMENT_DESIGNER:0 "Squad Designer"
 DEPLOYMENT_REMOVE_DIVISION:0 "Cancel Squad"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Recruit & Deploy"
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "Cannot §RDeploy§! a unit that would put us over the Squad's template cap"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RCannot delete this Template because $AMOUNT|H$ Squad(s) are using it.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RCannot delete this Template because $AMOUNT|H$ Squad(s) are transitioning from this template to new one (Waiting for receiving equipment matching new template).§!"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "This deployment creates Squads using $TEMPLATE|H$ template."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Increase the number of serial training of Squads that each line will complete.\n\nSetting to infinite means each line will train a new Squad when a previous one is deployed."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "This is the amount of Squads that each line will train before being removed.\n\nSetting to infinite means each line will train a new Squad when a previous one is deployed."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Decrease the number of serial training of Squads that each line will complete.\n\nSetting to infinite means each line will train a new Squad when a previous one is deployed."
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNot enough manpower or equipment to train $DIVS|H$ of the Squads§!"
 EXCEEDING_DIVISION_CAP:0 "§RExceeding cap for Squad's template§!"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "Cannot train new special template Squad."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "As a §HGovernment in Exile§! we have to control a §HCapital§! to train new Squads."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "Cannot change to this template because that would case us to exceed our special forces cap"
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "Cannot change to this template because that would case us to exceed our Squad cap"
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "This Squad is using the special forces cap, because that is the lowest cap."
 DIVISION_CAP_OF_TEMPLATE:0 "This template has a cap of $NUM|Y$."
 DIVISION_CAP_USAGE_DESC:0 "You are currently fielding $USED|Y$ and training $IN_TRAINING|Y$ of our $CAP|Y$ allowed Squads for $NAME|Y$"
 DIVISION_CAP_LIMIT_DESC:0 "This Squad is using the template cap, because that is the lowest cap."
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "This leaves room for $TRAINABLE|Y$ Squad(s) using this template."