--Camera-- 
NDefines_Graphics.NFrontend.CAMERA_MIN_HEIGHT = 50.0

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {600, 1000, 1200}
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MIN = 1000.0
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF_MAX = 1200.0
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MIN = 1000.0
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MAX = 1200.0
NDefines_Graphics.NGraphics.RESOURCE_MAP_ICON_TEXT_CUTOFF = 1000
NDefines_Graphics.NGraphics.CAPITAL_ICON_CUTOFF = 1200


NDefines_Graphics.NInterface.SLOW_INTERFACE_THRESHOLD = 50000
